services: 
  xi: 
    build:
      context: ./
    pull_policy: build
    restart: always
    volumes:
      - db:/var/data  
    environment: 
      TOKEN: ${TOKEN}
      GUILD_IDS: ${GUILD_IDS} 
      BOT_ADMINS: ${BOT_ADMINS} 
volumes:
  db:
